title: Real Estate Photography
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
typography_spectrum: 0.3424340181518346
color:
  saturation: 0.9427681958768517
  brandStrength: 0.9031095979735255
  rhythmicContrast: 0.06965791317634284
  brandColors:
    - '#595241'
    - '#B8AE9C'
    - '#FFFFFF'
    - '#ACCFCC'
    - '#8A0917'
  lightness: 0.1078062546439469
layout_spectrum: 1
name: Dan Cook Photography
